name: Build Website Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Folder
        run: mkdir build

      - name: Copy Files
        run: |
          cp -r html build/
          cp -r css build/
          cp -r js build/

      - name: Create Zip
        run: zip -r school-app.zip build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: school-app
          path: school-app.zip

